### ISSUE TITLE
Specifying likelihoods with parallel = "external"

### ISSUE THREAD

**Issue by lionel68** [florianhartig/BayesianTools#72] opened 2017-11-10 12:57 UTC
I aim at submitting the runMCMC computation to a HPC cluster and to make my jobs more efficient I am trying to work out how to parallelize the code.

Below is some dummy code similar to what I am working on:

`obs <- runif(30,-2,2)

lik_par <- function(mat_par){
  pred <- apply(mat_par,1,function(par) rnorm(30,par[1],par[2]))
  diff <- pred - obs
  llValues <- dnorm(diff, sd = 1, log = TRUE)  
  return(colSums(llValues))
}

density <- function(par){
  d1 <- dnorm(par[1], 50, 25, log=TRUE) #prior on forest
  d2 <- dnorm(par[2], 10, 10, log=TRUE) #prior on agriculture
  return(d1 + d2)
}
sampler <- function(n=1){
  d1 <- rnorm(n, 50, 25)
  d2 <- rnorm(n, 10, 10)
  return(cbind(d1, d2))
}
prior <- createPrior(density, sampler, lower=rep(0.001,2),upper=rep(100, 2), best=NULL)

bTMP <- createBayesianSetup(lik_par,prior=prior,parallel = "external")

settings <- list(iterations = 6, nrChains = 2)
runMCMC(bayesianSetup = bTMP, settings = settings)`

This returns: 
`Error in if ((logfitness_x_prop[i, 1] - logfitness_X[i, 1] + r_extra[i]) >  : 
  missing value where TRUE/FALSE needed`

I guess that there might be some issue with the prior specification as the prior density / sampler return one value instead of a vector, but I am unsure about which dimensions I should give to the vector. I assume that this should be equal to the number of rows in the parameter matrix given as input to the likelihood function. But I do not know if the user can / should control it.

**Comment by lionel68** [comment] 2017-11-10 12:59
And my SessinInfo():
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_BE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_BE.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_BE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BayesianTools_0.1.3 reshape2_1.4.2      gdistance_1.2-1     Matrix_1.2-11       igraph_1.1.2        raster_2.5-8       
[7] sp_1.2-5

**Comment by lionel68** [comment] 2017-11-10 14:16
Note that I get the same error when using parallel=TRUE, which is what I might use in the end ...

**Comment by thednainus** [comment] 2018-02-01 10:45
I am getting the same error message. @lionel68, Did you discover what you were doing that was generating this error? Thanks!

**Comment by florianhartig** [comment] 2018-02-01 11:56
Hi guy,

@lionel68 , sorry, I might have forgotten to answer this question

a) if you have a model that can be parallelized (i.e. that doesn't write to file and doesn't have any memory problems that would prevent trivial parallelization via a standard R cluster), don't try to write your own parallel likelihood - with high likelihood, this will lead to errors. Instead, simply set parallel = T. 

b) that being said, if you set parallel = internal, you have to make sure that you program the likelihood correctly. Lionel, in your case, when you have a likelihood 

`lik_par <- function(mat_par){
pred <- apply(mat_par,1,function(par) rnorm(30,par[1],par[2]))
diff <- pred - obs
llValues <- dnorm(diff, sd = 1, log = TRUE)
return(colSums(llValues))
}`

then 

`llValues <- dnorm(diff, sd = 1, log = TRUE)`

return a value, and 

`colSums(llValues)`

produces an error, so this didn't run for me at all. That is probably the reason why it didn't work with parallel = T either. Did you test if the likelihood works? 

In general, if you program a likelihood that should work with parallel = external, make sure that it works both with a vector (1 evaluation) and matrix (several model evaluations) as input, in either case the result should be as many likelihood values as you provide model evaluations.

**Comment by thednainus** [comment] 2018-02-01 13:34
I think I am missing something, and sorry for bothering you. I am trying to create a function to calculate the likelihood in parallel. my script is very long and it is hard to make a reproducible version here.

In addition, my likelihood function gets several global variables and functions, so I am trying to set up a parallel version using the parallel r package.
So far my "parallel" version to calculate the likelihood is:

`a <- function (parMat){
  cl <- makeCluster(3)
  clusterExport(cl=cl, varlist=c("THETA", "dm", "dated.tree", "X0", "T0", "T1", "GAMMA", "SRCSIZE", "obj_fun")) #export global variables and functions
  if(is.matrix(parMat)){
    res = parallel::parApply(cl = cl, parMat, 1, obj_fun) #obj_fun is my function that receives a matrix and calculates the likelihood
  }
  else{
    parMat = matrix(p1, ncol =12)
    res = parallel::parApply(cl = cl, parMat, 1, obj_fun)
  }
  on.exit(stopCluster(cl))
  return(res)
  
}`

The function above does work if I try to calculate the likelihood if I provide (1) a matrix with row corresponding to a proposal and each column representing the parameters; or (2) a single evaluation (a vector) that I transform to matrix with 12 columns. 

However, when I use the function above in:
`bayesianSetup <- createBayesianSetup(likelihood = a , prior = prior, parallel = "external")`
`settings = list(iterations = 1000, nrChains = 1, thin = 100)`
`out <- runMCMC(bayesianSetup = bayesianSetup, settings = settings)`

I get the error ```
Error in if ((logfitness_x_prop[i, 1] - logfitness_X[i, 1] + r_extra[i]) >  : 
  missing value where TRUE/FALSE needed
```
The script does work if I set up the bayesian setup without using parallel and using my obj_fun that receives a matrix as parameters.
`bayesianSetup <- createBayesianSetup(likelihood = obj_fun , prior = prior)`

**Comment by florianhartig** [comment] 2018-02-01 15:16
Hi Fabricia,

the error message could have various reasons, essentially that just means that there was a problem when the createBayesianSetup was trying to evaluate the likelihood. It might be useful (and I will put this on the list) to provide a more meaningful error message by testing or returning what is actually coming back from the likelihood function.

That being said: again, see point a) above - we provide this option with parallel = "external" for models that cannot be called in parallel by R, for example because they modify global variables or write to a global file directory. 

If models can be called in parallel in R (in your case, this seems to be the case, because you use parApply, or you are making an error there?), don't use parallel = "external", just write a normal likelihood and set parallel = T in createBayesianSetup. 

Parallel = T will cause the createBayesianSetup to wrap the model call in parApply, so essentially what you do there by hand.

**Comment by thednainus** [comment] 2018-02-01 16:08
Hi Florian,

Thanks very much for replying my message.
I did try `parallel=T` when setting up the `createBayesianSetup`, and I get the same error message. What I start to question is whether setting `parallel=T` will create a conflict with my likelihood function above (that I named `"a"`). This is because in that function I say that I want to run my analysis in 3 cores. While, by setting up `parallel=T` will set up my analysis in 7 cores. Having said that, I also tried adding `parallel=3` in the `createBayesianSetup`, and I also get an error. Hence, I tried `parallel="external"`.

I just decide to try to run the analysis by **not** setting up parallel as in 
`bayesianSetup <- createBayesianSetup(likelihood = a , prior = prior)`
So I notice that in Activity Monitor (I use an iMac) I opened double of what I requested as in `cl <- makeCluster(3)`. For example, if I request `makeCluster(3)`, I have 6 R sessions open; similarly, if I set `makeCluster(2)`, I end up with 4 R sessions opened. So this is the first time I am using the "parallel" package.. so maybe this is expected?

However, I am not sure whether the creatBayesianSetup is really running anything in parallel, or the opened R sessions were just because I requested them.

**Comment by florianhartig** [comment] 2018-02-02 17:26
Hi Fabricia,

ah, ok, no, this is not how it works - if you use parallel = T, you should NOT create your own cluster. BT will create a cluster and parallelize the likelihood. On most computers, also HPC with MPI, it should recognize the cluster structure automatically, but if not, you can supply the necessary arguments to the setup. 

So again, if you use parallel = T, don't create a cluster and don't use any parallel functions such as parApply in your likelihood, just write a plain likelihood in R and let BT do the rest. 

If you can further parallelize a single likelihood execution (not sure if this is the case for you), you can do this, but you have to use parallel = "external". It should work if you program this as specified in the help. But again, first try parallel = T and see if this works for you, this is much less error prone.

**Comment by thednainus** [comment] 2018-02-04 20:24
Hi Florian,
Thanks very much for replying to my comments.

Yes, I did try to add `parallel = T`, but I keep getting the same error message. 

I did a function to calculate the likelihood that did work if I provided a matrix, or a single evaluation (a vector) that I transform to matrix. Even though the calculation a single likelihood works, when I set up the createBayesianSetup, and try to run the mcmc, it does not work. I am now running the analysis without parallel and check how long it will take for a longer chain. :)

Thanks very much again, I really appreciate it.
Cheers,
Fabricia.

**Comment by fkrauer** [comment] 2018-02-05 13:22
Hi Florian, hi all

I am fitting a dynamic model. Some of my parameters are fixed (a set of theta, including two gammas), some are estimated (two betas, and two other parameters). I use the `parallel=T` option in the BayesianSetup to run it parallel on a HPC cluster. It worked perfectly until I decided to fix the parameters I had been estimating (betas) and fit other parameters (gammas) of the same model. Now I get the same error message:

`Error in if ((logfitness_x_prop[i, 1] - logfitness_X[i, 1] + r_extra[i]) > : missing value where TRUE/FALSE needed`

Surprisingly, it works if I fit the gammas without the parallelization. My guess is that the error is in the evaluation of the acceptance, because `(logfitness_x_prop[i, 1] - logfitness_X[i, 1] + r_extra[i])` might not be calculated for some reason. Since it happens only for certain parameters and not for others (for the same data and the same model), it may have to do with the posterior being -Inf (or Inf). Is that possible? 

Cheers, Fabienne

**Comment by florianhartig** [comment] 2018-02-05 14:19
OK, it's difficult to say what's the problem without seeing your code. parallel = T just wraps the likelihood in a parApply, so it should work if your likelihood works in a parApply.

@thednainus , @fkrauer , if you can send me a reproducible example via email, we can have a look.

Best,
F

**Comment by thednainus** [comment] 2018-02-05 19:06
Hi Florian,
Sure, I can organize a reproducible example and send to your e-mail.
However, just a quick message to see whether I am really understanding what you mean about setting`parallel = T`.

You know the example you give when you check the `createPrior` documentation?
Assuming that I would like to run that example in parallel, could I just do the below?
`bayesianSetup <- createBayesianSetup(likelihood = ll, prior = prior, parallel = 2)`

**Comment by florianhartig** [comment] 2018-02-06 12:39
Hi Fabricia,

yes, exactly, this should work, but I just checked, it doesn't, which I can't explain at the moment. 

Give me a bit of time to look at what's going on here. Also, I have in the meantime received Fabienne's code, so I will look at this too.

**Comment by florianhartig** [comment] 2018-02-06 13:05
OK, I have the problem. 

@thednainus first of all, in general the answer is yes, it should work and, in general, it does work. Look at this example

```
library(BayesianTools)
prior = createUniformPrior(lower = c(-3,-3), upper = c(3,3))
ll <- function(x) sum(dnorm(x, log = TRUE)) 
bayesianSetup <- createBayesianSetup(likelihood = ll, prior = prior, parallel = 3)
out <- runMCMC(bayesianSetup = bayesianSetup)
```

The reason why parallelizing the example in the help didn't work is described here https://github.com/florianhartig/BayesianTools/issues/98 . Bottomline for you - if you use custom priors, check if this could be a problem. However, again, the error could be created by any number of issues. 

@fkrauer has send me some code in the meantime, we will look at this.

**Comment by thednainus** [comment] 2018-02-06 13:51
Hi Florian,

Thanks! I do have custom priors. However, I do not specify an lower and upper bound. So in theory it should work. So it could be a problem on my likelihood function. So I will send you my scripts :)

Cheers,
Fabricia.

**Comment by fkrauer** [comment] 2018-03-19 10:30
Hi Florian

I don't know if this issue has been resolved, but I just talked to someone with a completely different model who ran into the same issue as we all did. He mentioned that the problem occurs only if the parallel setting is used and if the target is -Inf. 

Cheers, Fabienne

**Comment by florianhartig** [comment] 2018-03-19 13:58
So, one reason for this could be issue https://github.com/florianhartig/BayesianTools/issues/98 , it is possible to specify a custom prior, and then overwrite this with an additional truncation in the setup, which then causes a crash because the prior sampler samples a lot of values that actually have no prior support, i.e. the sampler doesn't fit to the actual prior. We are just changing the interface so that users can't set upper / lower with custom priors. 

Could this be the reason for the problem?

**Comment by thednainus** [comment] 2018-03-19 17:58
Just as a note. I downloaded the development version of BT (as suggested by e-mail from your student Max), and parallel is now working for my case. I did create a prior setting up a lower and upper bound for it, and I set `parallel = 4`.

**Comment by florianhartig** [comment] 2018-03-21 14:24
Hi all, OK, I think this is now fully resolved. For the record, there were 2 problems

1. It was possible for the user to specify a sampler that was different from the prior density. This would cause the MCMCs to start with start values / other settings that were outside the prior. We currently fix this in https://github.com/florianhartig/BayesianTools/issues/98

2. With parallel = T, there was bug, if the MCMC was in a -Inf setting (e.g. start values outside the prior), and proposed a new -Inf value. This is now fixed in the development branch in https://github.com/florianhartig/BayesianTools/issues/98

So, when using the code from the development branch, taking care that prior sampler and density are properly configured, everything should work. I hope we can push this changes to CRAN soon.

**Closed by florianhartig** 2018-03-21 14:24 UTC
Labels: question
